// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/relay.proto

package relaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerPubkey    string                 `protobuf:"bytes,1,opt,name=peer_pubkey,json=peerPubkey,proto3" json:"peer_pubkey,omitempty"`
	Plaintext     []byte                 `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_proto_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetPeerPubkey() string {
	if x != nil {
		return x.PeerPubkey
	}
	return ""
}

func (x *SendRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Queued        bool                   `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_proto_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *SendResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_proto_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{2}
}

type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ReceivedMessage     `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_proto_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{3}
}

func (x *PollResponse) GetMessages() []*ReceivedMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ReceivedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPeer      string                 `protobuf:"bytes,1,opt,name=from_peer,json=fromPeer,proto3" json:"from_peer,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Plaintext     []byte                 `protobuf:"bytes,3,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceivedMessage) Reset() {
	*x = ReceivedMessage{}
	mi := &file_proto_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedMessage) ProtoMessage() {}

func (x *ReceivedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedMessage.ProtoReflect.Descriptor instead.
func (*ReceivedMessage) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{4}
}

func (x *ReceivedMessage) GetFromPeer() string {
	if x != nil {
		return x.FromPeer
	}
	return ""
}

func (x *ReceivedMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ReceivedMessage) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *ReceivedMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{5}
}

type RelayEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayEndpoint) Reset() {
	*x = RelayEndpoint{}
	mi := &file_proto_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayEndpoint) ProtoMessage() {}

func (x *RelayEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayEndpoint.ProtoReflect.Descriptor instead.
func (*RelayEndpoint) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{6}
}

func (x *RelayEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RelayStatusList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*RelayStatus         `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayStatusList) Reset() {
	*x = RelayStatusList{}
	mi := &file_proto_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStatusList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStatusList) ProtoMessage() {}

func (x *RelayStatusList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStatusList.ProtoReflect.Descriptor instead.
func (*RelayStatusList) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{7}
}

func (x *RelayStatusList) GetEndpoints() []*RelayStatus {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type RelayStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Reachable     bool                   `protobuf:"varint,2,opt,name=reachable,proto3" json:"reachable,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	BlackoutMode  bool                   `protobuf:"varint,5,opt,name=blackout_mode,json=blackoutMode,proto3" json:"blackout_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayStatus) Reset() {
	*x = RelayStatus{}
	mi := &file_proto_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStatus) ProtoMessage() {}

func (x *RelayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStatus.ProtoReflect.Descriptor instead.
func (*RelayStatus) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{8}
}

func (x *RelayStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RelayStatus) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *RelayStatus) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RelayStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *RelayStatus) GetBlackoutMode() bool {
	if x != nil {
		return x.BlackoutMode
	}
	return false
}

type IdentityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityInfo) Reset() {
	*x = IdentityInfo{}
	mi := &file_proto_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityInfo) ProtoMessage() {}

func (x *IdentityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityInfo.ProtoReflect.Descriptor instead.
func (*IdentityInfo) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{9}
}

func (x *IdentityInfo) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Pubkey        string                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{10}
}

func (x *PeerInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PeerInfo) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type TransportStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DhtConnected     bool                   `protobuf:"varint,1,opt,name=dht_connected,json=dhtConnected,proto3" json:"dht_connected,omitempty"`
	DiscoveredRelays int32                  `protobuf:"varint,2,opt,name=discovered_relays,json=discoveredRelays,proto3" json:"discovered_relays,omitempty"`
	Libp2PDirect     bool                   `protobuf:"varint,3,opt,name=libp2p_direct,json=libp2pDirect,proto3" json:"libp2p_direct,omitempty"`
	Libp2PCircuit    bool                   `protobuf:"varint,4,opt,name=libp2p_circuit,json=libp2pCircuit,proto3" json:"libp2p_circuit,omitempty"`
	DnsMode          string                 `protobuf:"bytes,5,opt,name=dns_mode,json=dnsMode,proto3" json:"dns_mode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransportStatusResponse) Reset() {
	*x = TransportStatusResponse{}
	mi := &file_proto_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportStatusResponse) ProtoMessage() {}

func (x *TransportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportStatusResponse.ProtoReflect.Descriptor instead.
func (*TransportStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{11}
}

func (x *TransportStatusResponse) GetDhtConnected() bool {
	if x != nil {
		return x.DhtConnected
	}
	return false
}

func (x *TransportStatusResponse) GetDiscoveredRelays() int32 {
	if x != nil {
		return x.DiscoveredRelays
	}
	return 0
}

func (x *TransportStatusResponse) GetLibp2PDirect() bool {
	if x != nil {
		return x.Libp2PDirect
	}
	return false
}

func (x *TransportStatusResponse) GetLibp2PCircuit() bool {
	if x != nil {
		return x.Libp2PCircuit
	}
	return false
}

func (x *TransportStatusResponse) GetDnsMode() string {
	if x != nil {
		return x.DnsMode
	}
	return ""
}

var File_proto_relay_proto protoreflect.FileDescriptor

const file_proto_relay_proto_rawDesc = "" +
	"\n" +
	"\x11proto/relay.proto\x12\arelaypb\"L\n" +
	"\vSendRequest\x12\x1f\n" +
	"\vpeer_pubkey\x18\x01 \x01(\tR\n" +
	"peerPubkey\x12\x1c\n" +
	"\tplaintext\x18\x02 \x01(\fR\tplaintext\"f\n" +
	"\fSendResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06queued\x18\x02 \x01(\bR\x06queued\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\"\r\n" +
	"\vPollRequest\"D\n" +
	"\fPollResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.relaypb.ReceivedMessageR\bmessages\"\x89\x01\n" +
	"\x0fReceivedMessage\x12\x1b\n" +
	"\tfrom_peer\x18\x01 \x01(\tR\bfromPeer\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1c\n" +
	"\tplaintext\x18\x03 \x01(\fR\tplaintext\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\a\n" +
	"\x05Empty\")\n" +
	"\rRelayEndpoint\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"E\n" +
	"\x0fRelayStatusList\x122\n" +
	"\tendpoints\x18\x01 \x03(\v2\x14.relaypb.RelayStatusR\tendpoints\"\xa8\x01\n" +
	"\vRelayStatus\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\treachable\x18\x02 \x01(\bR\treachable\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\x12#\n" +
	"\rblackout_mode\x18\x05 \x01(\bR\fblackoutMode\"&\n" +
	"\fIdentityInfo\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\">\n" +
	"\bPeerInfo\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\tR\x06pubkey\"\xd2\x01\n" +
	"\x17TransportStatusResponse\x12#\n" +
	"\rdht_connected\x18\x01 \x01(\bR\fdhtConnected\x12+\n" +
	"\x11discovered_relays\x18\x02 \x01(\x05R\x10discoveredRelays\x12#\n" +
	"\rlibp2p_direct\x18\x03 \x01(\bR\flibp2pDirect\x12%\n" +
	"\x0elibp2p_circuit\x18\x04 \x01(\bR\rlibp2pCircuit\x12\x19\n" +
	"\bdns_mode\x18\x05 \x01(\tR\adnsMode2\xd9\x03\n" +
	"\vRelayClient\x12:\n" +
	"\vSendMessage\x12\x14.relaypb.SendRequest\x1a\x15.relaypb.SendResponse\x12;\n" +
	"\fPollMessages\x12\x14.relaypb.PollRequest\x1a\x15.relaypb.PollResponse\x12:\n" +
	"\x0eGetRelayStatus\x12\x0e.relaypb.Empty\x1a\x18.relaypb.RelayStatusList\x122\n" +
	"\bAddRelay\x12\x16.relaypb.RelayEndpoint\x1a\x0e.relaypb.Empty\x125\n" +
	"\vRemoveRelay\x12\x16.relaypb.RelayEndpoint\x1a\x0e.relaypb.Empty\x124\n" +
	"\vGetIdentity\x12\x0e.relaypb.Empty\x1a\x15.relaypb.IdentityInfo\x12,\n" +
	"\aAddPeer\x12\x11.relaypb.PeerInfo\x1a\x0e.relaypb.Empty\x12F\n" +
	"\x12GetTransportStatus\x12\x0e.relaypb.Empty\x1a .relaypb.TransportStatusResponseB+Z)github.com/user/dns-transport/pkg/relaypbb\x06proto3"

var (
	file_proto_relay_proto_rawDescOnce sync.Once
	file_proto_relay_proto_rawDescData []byte
)

func file_proto_relay_proto_rawDescGZIP() []byte {
	file_proto_relay_proto_rawDescOnce.Do(func() {
		file_proto_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_relay_proto_rawDesc), len(file_proto_relay_proto_rawDesc)))
	})
	return file_proto_relay_proto_rawDescData
}

var file_proto_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_relay_proto_goTypes = []any{
	(*SendRequest)(nil),             // 0: relaypb.SendRequest
	(*SendResponse)(nil),            // 1: relaypb.SendResponse
	(*PollRequest)(nil),             // 2: relaypb.PollRequest
	(*PollResponse)(nil),            // 3: relaypb.PollResponse
	(*ReceivedMessage)(nil),         // 4: relaypb.ReceivedMessage
	(*Empty)(nil),                   // 5: relaypb.Empty
	(*RelayEndpoint)(nil),           // 6: relaypb.RelayEndpoint
	(*RelayStatusList)(nil),         // 7: relaypb.RelayStatusList
	(*RelayStatus)(nil),             // 8: relaypb.RelayStatus
	(*IdentityInfo)(nil),            // 9: relaypb.IdentityInfo
	(*PeerInfo)(nil),                // 10: relaypb.PeerInfo
	(*TransportStatusResponse)(nil), // 11: relaypb.TransportStatusResponse
}
var file_proto_relay_proto_depIdxs = []int32{
	4,  // 0: relaypb.PollResponse.messages:type_name -> relaypb.ReceivedMessage
	8,  // 1: relaypb.RelayStatusList.endpoints:type_name -> relaypb.RelayStatus
	0,  // 2: relaypb.RelayClient.SendMessage:input_type -> relaypb.SendRequest
	2,  // 3: relaypb.RelayClient.PollMessages:input_type -> relaypb.PollRequest
	5,  // 4: relaypb.RelayClient.GetRelayStatus:input_type -> relaypb.Empty
	6,  // 5: relaypb.RelayClient.AddRelay:input_type -> relaypb.RelayEndpoint
	6,  // 6: relaypb.RelayClient.RemoveRelay:input_type -> relaypb.RelayEndpoint
	5,  // 7: relaypb.RelayClient.GetIdentity:input_type -> relaypb.Empty
	10, // 8: relaypb.RelayClient.AddPeer:input_type -> relaypb.PeerInfo
	5,  // 9: relaypb.RelayClient.GetTransportStatus:input_type -> relaypb.Empty
	1,  // 10: relaypb.RelayClient.SendMessage:output_type -> relaypb.SendResponse
	3,  // 11: relaypb.RelayClient.PollMessages:output_type -> relaypb.PollResponse
	7,  // 12: relaypb.RelayClient.GetRelayStatus:output_type -> relaypb.RelayStatusList
	5,  // 13: relaypb.RelayClient.AddRelay:output_type -> relaypb.Empty
	5,  // 14: relaypb.RelayClient.RemoveRelay:output_type -> relaypb.Empty
	9,  // 15: relaypb.RelayClient.GetIdentity:output_type -> relaypb.IdentityInfo
	5,  // 16: relaypb.RelayClient.AddPeer:output_type -> relaypb.Empty
	11, // 17: relaypb.RelayClient.GetTransportStatus:output_type -> relaypb.TransportStatusResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_relay_proto_init() }
func file_proto_relay_proto_init() {
	if File_proto_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_relay_proto_rawDesc), len(file_proto_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_relay_proto_goTypes,
		DependencyIndexes: file_proto_relay_proto_depIdxs,
		MessageInfos:      file_proto_relay_proto_msgTypes,
	}.Build()
	File_proto_relay_proto = out.File
	file_proto_relay_proto_goTypes = nil
	file_proto_relay_proto_depIdxs = nil
}
