// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: proto/bridge.proto

package bridgepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	P2PBridge_DiscoverRelays_FullMethodName     = "/bridgepb.P2PBridge/DiscoverRelays"
	P2PBridge_AdvertiseRelay_FullMethodName     = "/bridgepb.P2PBridge/AdvertiseRelay"
	P2PBridge_ForwardDNSPacket_FullMethodName   = "/bridgepb.P2PBridge/ForwardDNSPacket"
	P2PBridge_IncomingDNS_FullMethodName        = "/bridgepb.P2PBridge/IncomingDNS"
	P2PBridge_RelayDNSPacket_FullMethodName     = "/bridgepb.P2PBridge/RelayDNSPacket"
	P2PBridge_GetTransportStatus_FullMethodName = "/bridgepb.P2PBridge/GetTransportStatus"
)

// P2PBridgeClient is the client API for P2PBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type P2PBridgeClient interface {
	DiscoverRelays(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RelayUpdate], error)
	AdvertiseRelay(ctx context.Context, in *AdvertiseRequest, opts ...grpc.CallOption) (*AdvertiseResponse, error)
	// Forward DNS response via libp2p circuit back to remote peer
	ForwardDNSPacket(ctx context.Context, in *DNSPacket, opts ...grpc.CallOption) (*Empty, error)
	// Stream of incoming DNS queries from remote peers via libp2p circuit
	IncomingDNS(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSPacket], error)
	// Bidirectional DNS relay
	RelayDNSPacket(ctx context.Context, in *DNSPacket, opts ...grpc.CallOption) (*DNSPacket, error)
	// Get current DHT and transport status
	GetTransportStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TransportStatus, error)
}

type p2PBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewP2PBridgeClient(cc grpc.ClientConnInterface) P2PBridgeClient {
	return &p2PBridgeClient{cc}
}

func (c *p2PBridgeClient) DiscoverRelays(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RelayUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &P2PBridge_ServiceDesc.Streams[0], P2PBridge_DiscoverRelays_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DiscoverRequest, RelayUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PBridge_DiscoverRelaysClient = grpc.ServerStreamingClient[RelayUpdate]

func (c *p2PBridgeClient) AdvertiseRelay(ctx context.Context, in *AdvertiseRequest, opts ...grpc.CallOption) (*AdvertiseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdvertiseResponse)
	err := c.cc.Invoke(ctx, P2PBridge_AdvertiseRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PBridgeClient) ForwardDNSPacket(ctx context.Context, in *DNSPacket, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, P2PBridge_ForwardDNSPacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PBridgeClient) IncomingDNS(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &P2PBridge_ServiceDesc.Streams[1], P2PBridge_IncomingDNS_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, DNSPacket]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PBridge_IncomingDNSClient = grpc.ServerStreamingClient[DNSPacket]

func (c *p2PBridgeClient) RelayDNSPacket(ctx context.Context, in *DNSPacket, opts ...grpc.CallOption) (*DNSPacket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSPacket)
	err := c.cc.Invoke(ctx, P2PBridge_RelayDNSPacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PBridgeClient) GetTransportStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TransportStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransportStatus)
	err := c.cc.Invoke(ctx, P2PBridge_GetTransportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// P2PBridgeServer is the server API for P2PBridge service.
// All implementations must embed UnimplementedP2PBridgeServer
// for forward compatibility.
type P2PBridgeServer interface {
	DiscoverRelays(*DiscoverRequest, grpc.ServerStreamingServer[RelayUpdate]) error
	AdvertiseRelay(context.Context, *AdvertiseRequest) (*AdvertiseResponse, error)
	// Forward DNS response via libp2p circuit back to remote peer
	ForwardDNSPacket(context.Context, *DNSPacket) (*Empty, error)
	// Stream of incoming DNS queries from remote peers via libp2p circuit
	IncomingDNS(*Empty, grpc.ServerStreamingServer[DNSPacket]) error
	// Bidirectional DNS relay
	RelayDNSPacket(context.Context, *DNSPacket) (*DNSPacket, error)
	// Get current DHT and transport status
	GetTransportStatus(context.Context, *Empty) (*TransportStatus, error)
	mustEmbedUnimplementedP2PBridgeServer()
}

// UnimplementedP2PBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedP2PBridgeServer struct{}

func (UnimplementedP2PBridgeServer) DiscoverRelays(*DiscoverRequest, grpc.ServerStreamingServer[RelayUpdate]) error {
	return status.Error(codes.Unimplemented, "method DiscoverRelays not implemented")
}
func (UnimplementedP2PBridgeServer) AdvertiseRelay(context.Context, *AdvertiseRequest) (*AdvertiseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvertiseRelay not implemented")
}
func (UnimplementedP2PBridgeServer) ForwardDNSPacket(context.Context, *DNSPacket) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardDNSPacket not implemented")
}
func (UnimplementedP2PBridgeServer) IncomingDNS(*Empty, grpc.ServerStreamingServer[DNSPacket]) error {
	return status.Error(codes.Unimplemented, "method IncomingDNS not implemented")
}
func (UnimplementedP2PBridgeServer) RelayDNSPacket(context.Context, *DNSPacket) (*DNSPacket, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayDNSPacket not implemented")
}
func (UnimplementedP2PBridgeServer) GetTransportStatus(context.Context, *Empty) (*TransportStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransportStatus not implemented")
}
func (UnimplementedP2PBridgeServer) mustEmbedUnimplementedP2PBridgeServer() {}
func (UnimplementedP2PBridgeServer) testEmbeddedByValue()                   {}

// UnsafeP2PBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to P2PBridgeServer will
// result in compilation errors.
type UnsafeP2PBridgeServer interface {
	mustEmbedUnimplementedP2PBridgeServer()
}

func RegisterP2PBridgeServer(s grpc.ServiceRegistrar, srv P2PBridgeServer) {
	// If the following call panics, it indicates UnimplementedP2PBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&P2PBridge_ServiceDesc, srv)
}

func _P2PBridge_DiscoverRelays_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DiscoverRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(P2PBridgeServer).DiscoverRelays(m, &grpc.GenericServerStream[DiscoverRequest, RelayUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PBridge_DiscoverRelaysServer = grpc.ServerStreamingServer[RelayUpdate]

func _P2PBridge_AdvertiseRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvertiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PBridgeServer).AdvertiseRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PBridge_AdvertiseRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PBridgeServer).AdvertiseRelay(ctx, req.(*AdvertiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PBridge_ForwardDNSPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DNSPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PBridgeServer).ForwardDNSPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PBridge_ForwardDNSPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PBridgeServer).ForwardDNSPacket(ctx, req.(*DNSPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PBridge_IncomingDNS_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(P2PBridgeServer).IncomingDNS(m, &grpc.GenericServerStream[Empty, DNSPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PBridge_IncomingDNSServer = grpc.ServerStreamingServer[DNSPacket]

func _P2PBridge_RelayDNSPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DNSPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PBridgeServer).RelayDNSPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PBridge_RelayDNSPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PBridgeServer).RelayDNSPacket(ctx, req.(*DNSPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PBridge_GetTransportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PBridgeServer).GetTransportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PBridge_GetTransportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PBridgeServer).GetTransportStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// P2PBridge_ServiceDesc is the grpc.ServiceDesc for P2PBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var P2PBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridgepb.P2PBridge",
	HandlerType: (*P2PBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdvertiseRelay",
			Handler:    _P2PBridge_AdvertiseRelay_Handler,
		},
		{
			MethodName: "ForwardDNSPacket",
			Handler:    _P2PBridge_ForwardDNSPacket_Handler,
		},
		{
			MethodName: "RelayDNSPacket",
			Handler:    _P2PBridge_RelayDNSPacket_Handler,
		},
		{
			MethodName: "GetTransportStatus",
			Handler:    _P2PBridge_GetTransportStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DiscoverRelays",
			Handler:       _P2PBridge_DiscoverRelays_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "IncomingDNS",
			Handler:       _P2PBridge_IncomingDNS_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/bridge.proto",
}
