// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/bridge.proto

package bridgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	DnsAddress    string                 `protobuf:"bytes,2,opt,name=dns_address,json=dnsAddress,proto3" json:"dns_address,omitempty"`
	Multiaddrs    []string               `protobuf:"bytes,3,rep,name=multiaddrs,proto3" json:"multiaddrs,omitempty"`
	Load          int32                  `protobuf:"varint,4,opt,name=load,proto3" json:"load,omitempty"`
	LastSeen      int64                  `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayInfo) Reset() {
	*x = RelayInfo{}
	mi := &file_proto_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayInfo) ProtoMessage() {}

func (x *RelayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayInfo.ProtoReflect.Descriptor instead.
func (*RelayInfo) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *RelayInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *RelayInfo) GetDnsAddress() string {
	if x != nil {
		return x.DnsAddress
	}
	return ""
}

func (x *RelayInfo) GetMultiaddrs() []string {
	if x != nil {
		return x.Multiaddrs
	}
	return nil
}

func (x *RelayInfo) GetLoad() int32 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *RelayInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxRelays     int32                  `protobuf:"varint,1,opt,name=max_relays,json=maxRelays,proto3" json:"max_relays,omitempty"`
	Subscribe     bool                   `protobuf:"varint,2,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_proto_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoverRequest) GetMaxRelays() int32 {
	if x != nil {
		return x.MaxRelays
	}
	return 0
}

func (x *DiscoverRequest) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

type RelayUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InitialBatch   bool                   `protobuf:"varint,1,opt,name=initial_batch,json=initialBatch,proto3" json:"initial_batch,omitempty"`
	Added          []*RelayInfo           `protobuf:"bytes,2,rep,name=added,proto3" json:"added,omitempty"`
	RemovedPeerIds []string               `protobuf:"bytes,3,rep,name=removed_peer_ids,json=removedPeerIds,proto3" json:"removed_peer_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RelayUpdate) Reset() {
	*x = RelayUpdate{}
	mi := &file_proto_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayUpdate) ProtoMessage() {}

func (x *RelayUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayUpdate.ProtoReflect.Descriptor instead.
func (*RelayUpdate) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *RelayUpdate) GetInitialBatch() bool {
	if x != nil {
		return x.InitialBatch
	}
	return false
}

func (x *RelayUpdate) GetAdded() []*RelayInfo {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *RelayUpdate) GetRemovedPeerIds() []string {
	if x != nil {
		return x.RemovedPeerIds
	}
	return nil
}

type AdvertiseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertiseRequest) Reset() {
	*x = AdvertiseRequest{}
	mi := &file_proto_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiseRequest) ProtoMessage() {}

func (x *AdvertiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiseRequest.ProtoReflect.Descriptor instead.
func (*AdvertiseRequest) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *AdvertiseRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *AdvertiseRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

type AdvertiseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PublicDnsAddr string                 `protobuf:"bytes,2,opt,name=public_dns_addr,json=publicDnsAddr,proto3" json:"public_dns_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertiseResponse) Reset() {
	*x = AdvertiseResponse{}
	mi := &file_proto_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiseResponse) ProtoMessage() {}

func (x *AdvertiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiseResponse.ProtoReflect.Descriptor instead.
func (*AdvertiseResponse) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *AdvertiseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdvertiseResponse) GetPublicDnsAddr() string {
	if x != nil {
		return x.PublicDnsAddr
	}
	return ""
}

type DNSPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	RemotePeerId  string                 `protobuf:"bytes,2,opt,name=remote_peer_id,json=remotePeerId,proto3" json:"remote_peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSPacket) Reset() {
	*x = DNSPacket{}
	mi := &file_proto_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSPacket) ProtoMessage() {}

func (x *DNSPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSPacket.ProtoReflect.Descriptor instead.
func (*DNSPacket) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *DNSPacket) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *DNSPacket) GetRemotePeerId() string {
	if x != nil {
		return x.RemotePeerId
	}
	return ""
}

type TransportStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DhtConnected     bool                   `protobuf:"varint,1,opt,name=dht_connected,json=dhtConnected,proto3" json:"dht_connected,omitempty"`
	PeersInDht       int32                  `protobuf:"varint,2,opt,name=peers_in_dht,json=peersInDht,proto3" json:"peers_in_dht,omitempty"`
	DiscoveredRelays int32                  `protobuf:"varint,3,opt,name=discovered_relays,json=discoveredRelays,proto3" json:"discovered_relays,omitempty"`
	Libp2PDirect     bool                   `protobuf:"varint,4,opt,name=libp2p_direct,json=libp2pDirect,proto3" json:"libp2p_direct,omitempty"`
	Libp2PCircuit    bool                   `protobuf:"varint,5,opt,name=libp2p_circuit,json=libp2pCircuit,proto3" json:"libp2p_circuit,omitempty"`
	DnsMode          string                 `protobuf:"bytes,6,opt,name=dns_mode,json=dnsMode,proto3" json:"dns_mode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransportStatus) Reset() {
	*x = TransportStatus{}
	mi := &file_proto_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportStatus) ProtoMessage() {}

func (x *TransportStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportStatus.ProtoReflect.Descriptor instead.
func (*TransportStatus) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *TransportStatus) GetDhtConnected() bool {
	if x != nil {
		return x.DhtConnected
	}
	return false
}

func (x *TransportStatus) GetPeersInDht() int32 {
	if x != nil {
		return x.PeersInDht
	}
	return 0
}

func (x *TransportStatus) GetDiscoveredRelays() int32 {
	if x != nil {
		return x.DiscoveredRelays
	}
	return 0
}

func (x *TransportStatus) GetLibp2PDirect() bool {
	if x != nil {
		return x.Libp2PDirect
	}
	return false
}

func (x *TransportStatus) GetLibp2PCircuit() bool {
	if x != nil {
		return x.Libp2PCircuit
	}
	return false
}

func (x *TransportStatus) GetDnsMode() string {
	if x != nil {
		return x.DnsMode
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{7}
}

var File_proto_bridge_proto protoreflect.FileDescriptor

const file_proto_bridge_proto_rawDesc = "" +
	"\n" +
	"\x12proto/bridge.proto\x12\bbridgepb\"\x96\x01\n" +
	"\tRelayInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1f\n" +
	"\vdns_address\x18\x02 \x01(\tR\n" +
	"dnsAddress\x12\x1e\n" +
	"\n" +
	"multiaddrs\x18\x03 \x03(\tR\n" +
	"multiaddrs\x12\x12\n" +
	"\x04load\x18\x04 \x01(\x05R\x04load\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x03R\blastSeen\"N\n" +
	"\x0fDiscoverRequest\x12\x1d\n" +
	"\n" +
	"max_relays\x18\x01 \x01(\x05R\tmaxRelays\x12\x1c\n" +
	"\tsubscribe\x18\x02 \x01(\bR\tsubscribe\"\x87\x01\n" +
	"\vRelayUpdate\x12#\n" +
	"\rinitial_batch\x18\x01 \x01(\bR\finitialBatch\x12)\n" +
	"\x05added\x18\x02 \x03(\v2\x13.bridgepb.RelayInfoR\x05added\x12(\n" +
	"\x10removed_peer_ids\x18\x03 \x03(\tR\x0eremovedPeerIds\"G\n" +
	"\x10AdvertiseRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x1f\n" +
	"\vlisten_addr\x18\x02 \x01(\tR\n" +
	"listenAddr\"U\n" +
	"\x11AdvertiseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fpublic_dns_addr\x18\x02 \x01(\tR\rpublicDnsAddr\"C\n" +
	"\tDNSPacket\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\x12$\n" +
	"\x0eremote_peer_id\x18\x02 \x01(\tR\fremotePeerId\"\xec\x01\n" +
	"\x0fTransportStatus\x12#\n" +
	"\rdht_connected\x18\x01 \x01(\bR\fdhtConnected\x12 \n" +
	"\fpeers_in_dht\x18\x02 \x01(\x05R\n" +
	"peersInDht\x12+\n" +
	"\x11discovered_relays\x18\x03 \x01(\x05R\x10discoveredRelays\x12#\n" +
	"\rlibp2p_direct\x18\x04 \x01(\bR\flibp2pDirect\x12%\n" +
	"\x0elibp2p_circuit\x18\x05 \x01(\bR\rlibp2pCircuit\x12\x19\n" +
	"\bdns_mode\x18\x06 \x01(\tR\adnsMode\"\a\n" +
	"\x05Empty2\x8b\x03\n" +
	"\tP2PBridge\x12D\n" +
	"\x0eDiscoverRelays\x12\x19.bridgepb.DiscoverRequest\x1a\x15.bridgepb.RelayUpdate0\x01\x12I\n" +
	"\x0eAdvertiseRelay\x12\x1a.bridgepb.AdvertiseRequest\x1a\x1b.bridgepb.AdvertiseResponse\x128\n" +
	"\x10ForwardDNSPacket\x12\x13.bridgepb.DNSPacket\x1a\x0f.bridgepb.Empty\x125\n" +
	"\vIncomingDNS\x12\x0f.bridgepb.Empty\x1a\x13.bridgepb.DNSPacket0\x01\x12:\n" +
	"\x0eRelayDNSPacket\x12\x13.bridgepb.DNSPacket\x1a\x13.bridgepb.DNSPacket\x12@\n" +
	"\x12GetTransportStatus\x12\x0f.bridgepb.Empty\x1a\x19.bridgepb.TransportStatusB,Z*github.com/user/dns-transport/pkg/bridgepbb\x06proto3"

var (
	file_proto_bridge_proto_rawDescOnce sync.Once
	file_proto_bridge_proto_rawDescData []byte
)

func file_proto_bridge_proto_rawDescGZIP() []byte {
	file_proto_bridge_proto_rawDescOnce.Do(func() {
		file_proto_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bridge_proto_rawDesc), len(file_proto_bridge_proto_rawDesc)))
	})
	return file_proto_bridge_proto_rawDescData
}

var file_proto_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_bridge_proto_goTypes = []any{
	(*RelayInfo)(nil),         // 0: bridgepb.RelayInfo
	(*DiscoverRequest)(nil),   // 1: bridgepb.DiscoverRequest
	(*RelayUpdate)(nil),       // 2: bridgepb.RelayUpdate
	(*AdvertiseRequest)(nil),  // 3: bridgepb.AdvertiseRequest
	(*AdvertiseResponse)(nil), // 4: bridgepb.AdvertiseResponse
	(*DNSPacket)(nil),         // 5: bridgepb.DNSPacket
	(*TransportStatus)(nil),   // 6: bridgepb.TransportStatus
	(*Empty)(nil),             // 7: bridgepb.Empty
}
var file_proto_bridge_proto_depIdxs = []int32{
	0, // 0: bridgepb.RelayUpdate.added:type_name -> bridgepb.RelayInfo
	1, // 1: bridgepb.P2PBridge.DiscoverRelays:input_type -> bridgepb.DiscoverRequest
	3, // 2: bridgepb.P2PBridge.AdvertiseRelay:input_type -> bridgepb.AdvertiseRequest
	5, // 3: bridgepb.P2PBridge.ForwardDNSPacket:input_type -> bridgepb.DNSPacket
	7, // 4: bridgepb.P2PBridge.IncomingDNS:input_type -> bridgepb.Empty
	5, // 5: bridgepb.P2PBridge.RelayDNSPacket:input_type -> bridgepb.DNSPacket
	7, // 6: bridgepb.P2PBridge.GetTransportStatus:input_type -> bridgepb.Empty
	2, // 7: bridgepb.P2PBridge.DiscoverRelays:output_type -> bridgepb.RelayUpdate
	4, // 8: bridgepb.P2PBridge.AdvertiseRelay:output_type -> bridgepb.AdvertiseResponse
	7, // 9: bridgepb.P2PBridge.ForwardDNSPacket:output_type -> bridgepb.Empty
	5, // 10: bridgepb.P2PBridge.IncomingDNS:output_type -> bridgepb.DNSPacket
	5, // 11: bridgepb.P2PBridge.RelayDNSPacket:output_type -> bridgepb.DNSPacket
	6, // 12: bridgepb.P2PBridge.GetTransportStatus:output_type -> bridgepb.TransportStatus
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bridge_proto_init() }
func file_proto_bridge_proto_init() {
	if File_proto_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bridge_proto_rawDesc), len(file_proto_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bridge_proto_goTypes,
		DependencyIndexes: file_proto_bridge_proto_depIdxs,
		MessageInfos:      file_proto_bridge_proto_msgTypes,
	}.Build()
	File_proto_bridge_proto = out.File
	file_proto_bridge_proto_goTypes = nil
	file_proto_bridge_proto_depIdxs = nil
}
