// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/relay.proto

package relaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayClient_SendMessage_FullMethodName        = "/relaypb.RelayClient/SendMessage"
	RelayClient_PollMessages_FullMethodName       = "/relaypb.RelayClient/PollMessages"
	RelayClient_GetRelayStatus_FullMethodName     = "/relaypb.RelayClient/GetRelayStatus"
	RelayClient_AddRelay_FullMethodName           = "/relaypb.RelayClient/AddRelay"
	RelayClient_RemoveRelay_FullMethodName        = "/relaypb.RelayClient/RemoveRelay"
	RelayClient_GetIdentity_FullMethodName        = "/relaypb.RelayClient/GetIdentity"
	RelayClient_AddPeer_FullMethodName            = "/relaypb.RelayClient/AddPeer"
	RelayClient_GetTransportStatus_FullMethodName = "/relaypb.RelayClient/GetTransportStatus"
	RelayClient_SendMedia_FullMethodName          = "/relaypb.RelayClient/SendMedia"
	RelayClient_GetMediaStatus_FullMethodName     = "/relaypb.RelayClient/GetMediaStatus"
	RelayClient_CancelSend_FullMethodName         = "/relaypb.RelayClient/CancelSend"
	RelayClient_SendMediaStream_FullMethodName    = "/relaypb.RelayClient/SendMediaStream"
	RelayClient_GenerateInviteCode_FullMethodName = "/relaypb.RelayClient/GenerateInviteCode"
	RelayClient_JoinViaCode_FullMethodName        = "/relaypb.RelayClient/JoinViaCode"
	RelayClient_RemovePeer_FullMethodName         = "/relaypb.RelayClient/RemovePeer"
	RelayClient_CreateGroup_FullMethodName        = "/relaypb.RelayClient/CreateGroup"
	RelayClient_ListGroups_FullMethodName         = "/relaypb.RelayClient/ListGroups"
	RelayClient_LeaveGroup_FullMethodName         = "/relaypb.RelayClient/LeaveGroup"
	RelayClient_RemoveGroupMember_FullMethodName  = "/relaypb.RelayClient/RemoveGroupMember"
)

// RelayClientClient is the client API for RelayClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayClientClient interface {
	SendMessage(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	PollMessages(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error)
	GetRelayStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RelayStatusList, error)
	AddRelay(ctx context.Context, in *RelayEndpoint, opts ...grpc.CallOption) (*Empty, error)
	RemoveRelay(ctx context.Context, in *RelayEndpoint, opts ...grpc.CallOption) (*Empty, error)
	GetIdentity(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentityInfo, error)
	AddPeer(ctx context.Context, in *PeerInfo, opts ...grpc.CallOption) (*Empty, error)
	GetTransportStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TransportStatusResponse, error)
	// New media RPCs
	SendMedia(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SendMediaResponse, error)
	GetMediaStatus(ctx context.Context, in *GetMediaStatusRequest, opts ...grpc.CallOption) (*MediaStatusResponse, error)
	CancelSend(ctx context.Context, in *CancelSendRequest, opts ...grpc.CallOption) (*Empty, error)
	SendMediaStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MediaUploadChunk, SendMediaResponse], error)
	GenerateInviteCode(ctx context.Context, in *GenerateInviteCodeRequest, opts ...grpc.CallOption) (*GenerateInviteCodeResponse, error)
	JoinViaCode(ctx context.Context, in *JoinViaCodeRequest, opts ...grpc.CallOption) (*Empty, error)
	RemovePeer(ctx context.Context, in *PeerInfo, opts ...grpc.CallOption) (*Empty, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	ListGroups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberRequest, opts ...grpc.CallOption) (*Empty, error)
}

type relayClientClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayClientClient(cc grpc.ClientConnInterface) RelayClientClient {
	return &relayClientClient{cc}
}

func (c *relayClientClient) SendMessage(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, RelayClient_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) PollMessages(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollResponse)
	err := c.cc.Invoke(ctx, RelayClient_PollMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) GetRelayStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RelayStatusList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayStatusList)
	err := c.cc.Invoke(ctx, RelayClient_GetRelayStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) AddRelay(ctx context.Context, in *RelayEndpoint, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_AddRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) RemoveRelay(ctx context.Context, in *RelayEndpoint, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_RemoveRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) GetIdentity(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentityInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityInfo)
	err := c.cc.Invoke(ctx, RelayClient_GetIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) AddPeer(ctx context.Context, in *PeerInfo, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_AddPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) GetTransportStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TransportStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransportStatusResponse)
	err := c.cc.Invoke(ctx, RelayClient_GetTransportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) SendMedia(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SendMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMediaResponse)
	err := c.cc.Invoke(ctx, RelayClient_SendMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) GetMediaStatus(ctx context.Context, in *GetMediaStatusRequest, opts ...grpc.CallOption) (*MediaStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MediaStatusResponse)
	err := c.cc.Invoke(ctx, RelayClient_GetMediaStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) CancelSend(ctx context.Context, in *CancelSendRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_CancelSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) SendMediaStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MediaUploadChunk, SendMediaResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RelayClient_ServiceDesc.Streams[0], RelayClient_SendMediaStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MediaUploadChunk, SendMediaResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayClient_SendMediaStreamClient = grpc.ClientStreamingClient[MediaUploadChunk, SendMediaResponse]

func (c *relayClientClient) GenerateInviteCode(ctx context.Context, in *GenerateInviteCodeRequest, opts ...grpc.CallOption) (*GenerateInviteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateInviteCodeResponse)
	err := c.cc.Invoke(ctx, RelayClient_GenerateInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) JoinViaCode(ctx context.Context, in *JoinViaCodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_JoinViaCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) RemovePeer(ctx context.Context, in *PeerInfo, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_RemovePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, RelayClient_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) ListGroups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, RelayClient_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_RemoveGroupMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayClientServer is the server API for RelayClient service.
// All implementations must embed UnimplementedRelayClientServer
// for forward compatibility.
type RelayClientServer interface {
	SendMessage(context.Context, *SendRequest) (*SendResponse, error)
	PollMessages(context.Context, *PollRequest) (*PollResponse, error)
	GetRelayStatus(context.Context, *Empty) (*RelayStatusList, error)
	AddRelay(context.Context, *RelayEndpoint) (*Empty, error)
	RemoveRelay(context.Context, *RelayEndpoint) (*Empty, error)
	GetIdentity(context.Context, *Empty) (*IdentityInfo, error)
	AddPeer(context.Context, *PeerInfo) (*Empty, error)
	GetTransportStatus(context.Context, *Empty) (*TransportStatusResponse, error)
	// New media RPCs
	SendMedia(context.Context, *SendMediaRequest) (*SendMediaResponse, error)
	GetMediaStatus(context.Context, *GetMediaStatusRequest) (*MediaStatusResponse, error)
	CancelSend(context.Context, *CancelSendRequest) (*Empty, error)
	SendMediaStream(grpc.ClientStreamingServer[MediaUploadChunk, SendMediaResponse]) error
	GenerateInviteCode(context.Context, *GenerateInviteCodeRequest) (*GenerateInviteCodeResponse, error)
	JoinViaCode(context.Context, *JoinViaCodeRequest) (*Empty, error)
	RemovePeer(context.Context, *PeerInfo) (*Empty, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	ListGroups(context.Context, *Empty) (*ListGroupsResponse, error)
	LeaveGroup(context.Context, *LeaveGroupRequest) (*Empty, error)
	RemoveGroupMember(context.Context, *RemoveGroupMemberRequest) (*Empty, error)
	mustEmbedUnimplementedRelayClientServer()
}

// UnimplementedRelayClientServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayClientServer struct{}

func (UnimplementedRelayClientServer) SendMessage(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedRelayClientServer) PollMessages(context.Context, *PollRequest) (*PollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollMessages not implemented")
}
func (UnimplementedRelayClientServer) GetRelayStatus(context.Context, *Empty) (*RelayStatusList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelayStatus not implemented")
}
func (UnimplementedRelayClientServer) AddRelay(context.Context, *RelayEndpoint) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRelay not implemented")
}
func (UnimplementedRelayClientServer) RemoveRelay(context.Context, *RelayEndpoint) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRelay not implemented")
}
func (UnimplementedRelayClientServer) GetIdentity(context.Context, *Empty) (*IdentityInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentity not implemented")
}
func (UnimplementedRelayClientServer) AddPeer(context.Context, *PeerInfo) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPeer not implemented")
}
func (UnimplementedRelayClientServer) GetTransportStatus(context.Context, *Empty) (*TransportStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransportStatus not implemented")
}
func (UnimplementedRelayClientServer) SendMedia(context.Context, *SendMediaRequest) (*SendMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMedia not implemented")
}
func (UnimplementedRelayClientServer) GetMediaStatus(context.Context, *GetMediaStatusRequest) (*MediaStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMediaStatus not implemented")
}
func (UnimplementedRelayClientServer) CancelSend(context.Context, *CancelSendRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelSend not implemented")
}
func (UnimplementedRelayClientServer) SendMediaStream(grpc.ClientStreamingServer[MediaUploadChunk, SendMediaResponse]) error {
	return status.Error(codes.Unimplemented, "method SendMediaStream not implemented")
}
func (UnimplementedRelayClientServer) GenerateInviteCode(context.Context, *GenerateInviteCodeRequest) (*GenerateInviteCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateInviteCode not implemented")
}
func (UnimplementedRelayClientServer) JoinViaCode(context.Context, *JoinViaCodeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinViaCode not implemented")
}
func (UnimplementedRelayClientServer) RemovePeer(context.Context, *PeerInfo) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePeer not implemented")
}
func (UnimplementedRelayClientServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedRelayClientServer) ListGroups(context.Context, *Empty) (*ListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedRelayClientServer) LeaveGroup(context.Context, *LeaveGroupRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedRelayClientServer) RemoveGroupMember(context.Context, *RemoveGroupMemberRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGroupMember not implemented")
}
func (UnimplementedRelayClientServer) mustEmbedUnimplementedRelayClientServer() {}
func (UnimplementedRelayClientServer) testEmbeddedByValue()                     {}

// UnsafeRelayClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayClientServer will
// result in compilation errors.
type UnsafeRelayClientServer interface {
	mustEmbedUnimplementedRelayClientServer()
}

func RegisterRelayClientServer(s grpc.ServiceRegistrar, srv RelayClientServer) {
	// If the following call panics, it indicates UnimplementedRelayClientServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayClient_ServiceDesc, srv)
}

func _RelayClient_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).SendMessage(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_PollMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).PollMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_PollMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).PollMessages(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_GetRelayStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).GetRelayStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_GetRelayStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).GetRelayStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_AddRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayEndpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).AddRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_AddRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).AddRelay(ctx, req.(*RelayEndpoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_RemoveRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayEndpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).RemoveRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_RemoveRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).RemoveRelay(ctx, req.(*RelayEndpoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_GetIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).GetIdentity(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_AddPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).AddPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_AddPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).AddPeer(ctx, req.(*PeerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_GetTransportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).GetTransportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_GetTransportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).GetTransportStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_SendMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).SendMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_SendMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).SendMedia(ctx, req.(*SendMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_GetMediaStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).GetMediaStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_GetMediaStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).GetMediaStatus(ctx, req.(*GetMediaStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_CancelSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).CancelSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_CancelSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).CancelSend(ctx, req.(*CancelSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_SendMediaStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RelayClientServer).SendMediaStream(&grpc.GenericServerStream[MediaUploadChunk, SendMediaResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayClient_SendMediaStreamServer = grpc.ClientStreamingServer[MediaUploadChunk, SendMediaResponse]

func _RelayClient_GenerateInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateInviteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).GenerateInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_GenerateInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).GenerateInviteCode(ctx, req.(*GenerateInviteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_JoinViaCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinViaCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).JoinViaCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_JoinViaCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).JoinViaCode(ctx, req.(*JoinViaCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_RemovePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).RemovePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_RemovePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).RemovePeer(ctx, req.(*PeerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).ListGroups(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).LeaveGroup(ctx, req.(*LeaveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_RemoveGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveGroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).RemoveGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_RemoveGroupMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).RemoveGroupMember(ctx, req.(*RemoveGroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayClient_ServiceDesc is the grpc.ServiceDesc for RelayClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relaypb.RelayClient",
	HandlerType: (*RelayClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _RelayClient_SendMessage_Handler,
		},
		{
			MethodName: "PollMessages",
			Handler:    _RelayClient_PollMessages_Handler,
		},
		{
			MethodName: "GetRelayStatus",
			Handler:    _RelayClient_GetRelayStatus_Handler,
		},
		{
			MethodName: "AddRelay",
			Handler:    _RelayClient_AddRelay_Handler,
		},
		{
			MethodName: "RemoveRelay",
			Handler:    _RelayClient_RemoveRelay_Handler,
		},
		{
			MethodName: "GetIdentity",
			Handler:    _RelayClient_GetIdentity_Handler,
		},
		{
			MethodName: "AddPeer",
			Handler:    _RelayClient_AddPeer_Handler,
		},
		{
			MethodName: "GetTransportStatus",
			Handler:    _RelayClient_GetTransportStatus_Handler,
		},
		{
			MethodName: "SendMedia",
			Handler:    _RelayClient_SendMedia_Handler,
		},
		{
			MethodName: "GetMediaStatus",
			Handler:    _RelayClient_GetMediaStatus_Handler,
		},
		{
			MethodName: "CancelSend",
			Handler:    _RelayClient_CancelSend_Handler,
		},
		{
			MethodName: "GenerateInviteCode",
			Handler:    _RelayClient_GenerateInviteCode_Handler,
		},
		{
			MethodName: "JoinViaCode",
			Handler:    _RelayClient_JoinViaCode_Handler,
		},
		{
			MethodName: "RemovePeer",
			Handler:    _RelayClient_RemovePeer_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _RelayClient_CreateGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _RelayClient_ListGroups_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _RelayClient_LeaveGroup_Handler,
		},
		{
			MethodName: "RemoveGroupMember",
			Handler:    _RelayClient_RemoveGroupMember_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMediaStream",
			Handler:       _RelayClient_SendMediaStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/relay.proto",
}
