// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: relay.proto

package relaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMediaRequest_Transport int32

const (
	SendMediaRequest_AUTO SendMediaRequest_Transport = 0
	SendMediaRequest_DNS  SendMediaRequest_Transport = 1
)

// Enum value maps for SendMediaRequest_Transport.
var (
	SendMediaRequest_Transport_name = map[int32]string{
		0: "AUTO",
		1: "DNS",
	}
	SendMediaRequest_Transport_value = map[string]int32{
		"AUTO": 0,
		"DNS":  1,
	}
)

func (x SendMediaRequest_Transport) Enum() *SendMediaRequest_Transport {
	p := new(SendMediaRequest_Transport)
	*p = x
	return p
}

func (x SendMediaRequest_Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendMediaRequest_Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[0].Descriptor()
}

func (SendMediaRequest_Transport) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[0]
}

func (x SendMediaRequest_Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendMediaRequest_Transport.Descriptor instead.
func (SendMediaRequest_Transport) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0, 0}
}

type MediaStatusResponse_Status int32

const (
	MediaStatusResponse_QUEUED   MediaStatusResponse_Status = 0
	MediaStatusResponse_SENDING  MediaStatusResponse_Status = 1
	MediaStatusResponse_ARRIVING MediaStatusResponse_Status = 2
	MediaStatusResponse_COMPLETE MediaStatusResponse_Status = 3
	MediaStatusResponse_FAILED   MediaStatusResponse_Status = 4
)

// Enum value maps for MediaStatusResponse_Status.
var (
	MediaStatusResponse_Status_name = map[int32]string{
		0: "QUEUED",
		1: "SENDING",
		2: "ARRIVING",
		3: "COMPLETE",
		4: "FAILED",
	}
	MediaStatusResponse_Status_value = map[string]int32{
		"QUEUED":   0,
		"SENDING":  1,
		"ARRIVING": 2,
		"COMPLETE": 3,
		"FAILED":   4,
	}
)

func (x MediaStatusResponse_Status) Enum() *MediaStatusResponse_Status {
	p := new(MediaStatusResponse_Status)
	*p = x
	return p
}

func (x MediaStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[1].Descriptor()
}

func (MediaStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[1]
}

func (x MediaStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaStatusResponse_Status.Descriptor instead.
func (MediaStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3, 0}
}

type SendMediaRequest struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	PeerPubkey         string                     `protobuf:"bytes,1,opt,name=peer_pubkey,json=peerPubkey,proto3" json:"peer_pubkey,omitempty"`
	MediaData          []byte                     `protobuf:"bytes,2,opt,name=media_data,json=mediaData,proto3" json:"media_data,omitempty"`
	Filename           string                     `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType           string                     `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	PreferredTransport SendMediaRequest_Transport `protobuf:"varint,5,opt,name=preferred_transport,json=preferredTransport,proto3,enum=relaypb.SendMediaRequest_Transport" json:"preferred_transport,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SendMediaRequest) Reset() {
	*x = SendMediaRequest{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMediaRequest) ProtoMessage() {}

func (x *SendMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMediaRequest.ProtoReflect.Descriptor instead.
func (*SendMediaRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *SendMediaRequest) GetPeerPubkey() string {
	if x != nil {
		return x.PeerPubkey
	}
	return ""
}

func (x *SendMediaRequest) GetMediaData() []byte {
	if x != nil {
		return x.MediaData
	}
	return nil
}

func (x *SendMediaRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SendMediaRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *SendMediaRequest) GetPreferredTransport() SendMediaRequest_Transport {
	if x != nil {
		return x.PreferredTransport
	}
	return SendMediaRequest_AUTO
}

type SendMediaResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	EstimatedSeconds int32                  `protobuf:"varint,2,opt,name=estimated_seconds,json=estimatedSeconds,proto3" json:"estimated_seconds,omitempty"`
	Transport        string                 `protobuf:"bytes,3,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMediaResponse) Reset() {
	*x = SendMediaResponse{}
	mi := &file_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMediaResponse) ProtoMessage() {}

func (x *SendMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMediaResponse.ProtoReflect.Descriptor instead.
func (*SendMediaResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *SendMediaResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMediaResponse) GetEstimatedSeconds() int32 {
	if x != nil {
		return x.EstimatedSeconds
	}
	return 0
}

func (x *SendMediaResponse) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

type GetMediaStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaStatusRequest) Reset() {
	*x = GetMediaStatusRequest{}
	mi := &file_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaStatusRequest) ProtoMessage() {}

func (x *GetMediaStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMediaStatusRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *GetMediaStatusRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type MediaStatusResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	MessageId     string                     `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        MediaStatusResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=relaypb.MediaStatusResponse_Status" json:"status,omitempty"`
	ProgressPct   int32                      `protobuf:"varint,3,opt,name=progress_pct,json=progressPct,proto3" json:"progress_pct,omitempty"`
	Error         string                     `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaStatusResponse) Reset() {
	*x = MediaStatusResponse{}
	mi := &file_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaStatusResponse) ProtoMessage() {}

func (x *MediaStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaStatusResponse.ProtoReflect.Descriptor instead.
func (*MediaStatusResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3}
}

func (x *MediaStatusResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MediaStatusResponse) GetStatus() MediaStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return MediaStatusResponse_QUEUED
}

func (x *MediaStatusResponse) GetProgressPct() int32 {
	if x != nil {
		return x.ProgressPct
	}
	return 0
}

func (x *MediaStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSendRequest) Reset() {
	*x = CancelSendRequest{}
	mi := &file_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSendRequest) ProtoMessage() {}

func (x *CancelSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSendRequest.ProtoReflect.Descriptor instead.
func (*CancelSendRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{4}
}

func (x *CancelSendRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type MediaUploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUploadChunk) Reset() {
	*x = MediaUploadChunk{}
	mi := &file_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUploadChunk) ProtoMessage() {}

func (x *MediaUploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUploadChunk.ProtoReflect.Descriptor instead.
func (*MediaUploadChunk) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5}
}

func (x *MediaUploadChunk) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *MediaUploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MediaUploadChunk) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type SendRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeerPubkey        string                 `protobuf:"bytes,1,opt,name=peer_pubkey,json=peerPubkey,proto3" json:"peer_pubkey,omitempty"`
	Plaintext         []byte                 `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	ClientTimestampMs uint64                 `protobuf:"varint,3,opt,name=client_timestamp_ms,json=clientTimestampMs,proto3" json:"client_timestamp_ms,omitempty"`
	GroupId           string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{6}
}

func (x *SendRequest) GetPeerPubkey() string {
	if x != nil {
		return x.PeerPubkey
	}
	return ""
}

func (x *SendRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *SendRequest) GetClientTimestampMs() uint64 {
	if x != nil {
		return x.ClientTimestampMs
	}
	return 0
}

func (x *SendRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Queued        bool                   `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{7}
}

func (x *SendResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *SendResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{8}
}

type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ReceivedMessage     `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{9}
}

func (x *PollResponse) GetMessages() []*ReceivedMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ReceivedMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromPeer          string                 `protobuf:"bytes,1,opt,name=from_peer,json=fromPeer,proto3" json:"from_peer,omitempty"`
	MessageId         string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Plaintext         []byte                 `protobuf:"bytes,3,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Timestamp         int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ServerTimestampMs uint64                 `protobuf:"varint,5,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"`
	SequenceNumber    uint64                 `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	GroupId           string                 `protobuf:"bytes,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReceivedMessage) Reset() {
	*x = ReceivedMessage{}
	mi := &file_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedMessage) ProtoMessage() {}

func (x *ReceivedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedMessage.ProtoReflect.Descriptor instead.
func (*ReceivedMessage) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{10}
}

func (x *ReceivedMessage) GetFromPeer() string {
	if x != nil {
		return x.FromPeer
	}
	return ""
}

func (x *ReceivedMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ReceivedMessage) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *ReceivedMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReceivedMessage) GetServerTimestampMs() uint64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

func (x *ReceivedMessage) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ReceivedMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{11}
}

type RelayEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayEndpoint) Reset() {
	*x = RelayEndpoint{}
	mi := &file_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayEndpoint) ProtoMessage() {}

func (x *RelayEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayEndpoint.ProtoReflect.Descriptor instead.
func (*RelayEndpoint) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{12}
}

func (x *RelayEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RelayStatusList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*RelayStatus         `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayStatusList) Reset() {
	*x = RelayStatusList{}
	mi := &file_relay_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStatusList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStatusList) ProtoMessage() {}

func (x *RelayStatusList) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStatusList.ProtoReflect.Descriptor instead.
func (*RelayStatusList) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{13}
}

func (x *RelayStatusList) GetEndpoints() []*RelayStatus {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type RelayStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Reachable     bool                   `protobuf:"varint,2,opt,name=reachable,proto3" json:"reachable,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	BlackoutMode  bool                   `protobuf:"varint,5,opt,name=blackout_mode,json=blackoutMode,proto3" json:"blackout_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayStatus) Reset() {
	*x = RelayStatus{}
	mi := &file_relay_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStatus) ProtoMessage() {}

func (x *RelayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStatus.ProtoReflect.Descriptor instead.
func (*RelayStatus) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{14}
}

func (x *RelayStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RelayStatus) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *RelayStatus) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RelayStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *RelayStatus) GetBlackoutMode() bool {
	if x != nil {
		return x.BlackoutMode
	}
	return false
}

type IdentityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityInfo) Reset() {
	*x = IdentityInfo{}
	mi := &file_relay_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityInfo) ProtoMessage() {}

func (x *IdentityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityInfo.ProtoReflect.Descriptor instead.
func (*IdentityInfo) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{15}
}

func (x *IdentityInfo) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *IdentityInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *IdentityInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Pubkey        string                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_relay_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{16}
}

func (x *PeerInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PeerInfo) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type GenerateInviteCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInviteCodeRequest) Reset() {
	*x = GenerateInviteCodeRequest{}
	mi := &file_relay_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInviteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInviteCodeRequest) ProtoMessage() {}

func (x *GenerateInviteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInviteCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateInviteCodeRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{17}
}

func (x *GenerateInviteCodeRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type GenerateInviteCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInviteCodeResponse) Reset() {
	*x = GenerateInviteCodeResponse{}
	mi := &file_relay_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInviteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInviteCodeResponse) ProtoMessage() {}

func (x *GenerateInviteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInviteCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateInviteCodeResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateInviteCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type JoinViaCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinViaCodeRequest) Reset() {
	*x = JoinViaCodeRequest{}
	mi := &file_relay_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinViaCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinViaCodeRequest) ProtoMessage() {}

func (x *JoinViaCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinViaCodeRequest.ProtoReflect.Descriptor instead.
func (*JoinViaCodeRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{19}
}

func (x *JoinViaCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type JoinViaCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerNickname  string                 `protobuf:"bytes,1,opt,name=peer_nickname,json=peerNickname,proto3" json:"peer_nickname,omitempty"`
	PeerPubkey    string                 `protobuf:"bytes,2,opt,name=peer_pubkey,json=peerPubkey,proto3" json:"peer_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinViaCodeResponse) Reset() {
	*x = JoinViaCodeResponse{}
	mi := &file_relay_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinViaCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinViaCodeResponse) ProtoMessage() {}

func (x *JoinViaCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinViaCodeResponse.ProtoReflect.Descriptor instead.
func (*JoinViaCodeResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{20}
}

func (x *JoinViaCodeResponse) GetPeerNickname() string {
	if x != nil {
		return x.PeerNickname
	}
	return ""
}

func (x *JoinViaCodeResponse) GetPeerPubkey() string {
	if x != nil {
		return x.PeerPubkey
	}
	return ""
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_relay_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{21}
}

func (x *ListPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MemberPubkeys []string               `protobuf:"bytes,2,rep,name=member_pubkeys,json=memberPubkeys,proto3" json:"member_pubkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_relay_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{22}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetMemberPubkeys() []string {
	if x != nil {
		return x.MemberPubkeys
	}
	return nil
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_relay_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{23}
}

func (x *CreateGroupResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type LeaveGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupRequest) Reset() {
	*x = LeaveGroupRequest{}
	mi := &file_relay_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupRequest) ProtoMessage() {}

func (x *LeaveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupRequest.ProtoReflect.Descriptor instead.
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{24}
}

func (x *LeaveGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type RemoveGroupMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberPubkey  string                 `protobuf:"bytes,2,opt,name=member_pubkey,json=memberPubkey,proto3" json:"member_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupMemberRequest) Reset() {
	*x = RemoveGroupMemberRequest{}
	mi := &file_relay_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberRequest) ProtoMessage() {}

func (x *RemoveGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveGroupMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemoveGroupMemberRequest) GetMemberPubkey() string {
	if x != nil {
		return x.MemberPubkey
	}
	return ""
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupInfo           `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_relay_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{26}
}

func (x *ListGroupsResponse) GetGroups() []*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AdminPubkey   string                 `protobuf:"bytes,3,opt,name=admin_pubkey,json=adminPubkey,proto3" json:"admin_pubkey,omitempty"`
	Members       []*GroupMember         `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	KeyEpoch      uint64                 `protobuf:"varint,5,opt,name=key_epoch,json=keyEpoch,proto3" json:"key_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_relay_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{27}
}

func (x *GroupInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetAdminPubkey() string {
	if x != nil {
		return x.AdminPubkey
	}
	return ""
}

func (x *GroupInfo) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GroupInfo) GetKeyEpoch() uint64 {
	if x != nil {
		return x.KeyEpoch
	}
	return 0
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_relay_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{28}
}

func (x *GroupMember) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *GroupMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type TransportStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DhtConnected     bool                   `protobuf:"varint,1,opt,name=dht_connected,json=dhtConnected,proto3" json:"dht_connected,omitempty"`
	DiscoveredRelays int32                  `protobuf:"varint,2,opt,name=discovered_relays,json=discoveredRelays,proto3" json:"discovered_relays,omitempty"`
	DnsMode          string                 `protobuf:"bytes,5,opt,name=dns_mode,json=dnsMode,proto3" json:"dns_mode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransportStatusResponse) Reset() {
	*x = TransportStatusResponse{}
	mi := &file_relay_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportStatusResponse) ProtoMessage() {}

func (x *TransportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportStatusResponse.ProtoReflect.Descriptor instead.
func (*TransportStatusResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{29}
}

func (x *TransportStatusResponse) GetDhtConnected() bool {
	if x != nil {
		return x.DhtConnected
	}
	return false
}

func (x *TransportStatusResponse) GetDiscoveredRelays() int32 {
	if x != nil {
		return x.DiscoveredRelays
	}
	return 0
}

func (x *TransportStatusResponse) GetDnsMode() string {
	if x != nil {
		return x.DnsMode
	}
	return ""
}

// Profile messages
type ProfileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileInfo) Reset() {
	*x = ProfileInfo{}
	mi := &file_relay_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileInfo) ProtoMessage() {}

func (x *ProfileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileInfo.ProtoReflect.Descriptor instead.
func (*ProfileInfo) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{30}
}

func (x *ProfileInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type SetProfilePicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProfilePicRequest) Reset() {
	*x = SetProfilePicRequest{}
	mi := &file_relay_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProfilePicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfilePicRequest) ProtoMessage() {}

func (x *SetProfilePicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfilePicRequest.ProtoReflect.Descriptor instead.
func (*SetProfilePicRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{31}
}

func (x *SetProfilePicRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *SetProfilePicRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type ProfilePicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilePicResponse) Reset() {
	*x = ProfilePicResponse{}
	mi := &file_relay_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilePicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePicResponse) ProtoMessage() {}

func (x *ProfilePicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilePicResponse.ProtoReflect.Descriptor instead.
func (*ProfilePicResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{32}
}

func (x *ProfilePicResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ProfilePicResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

var File_relay_proto protoreflect.FileDescriptor

const file_relay_proto_rawDesc = "" +
	"\n" +
	"\vrelay.proto\x12\arelaypb\"\x8d\x02\n" +
	"\x10SendMediaRequest\x12\x1f\n" +
	"\vpeer_pubkey\x18\x01 \x01(\tR\n" +
	"peerPubkey\x12\x1d\n" +
	"\n" +
	"media_data\x18\x02 \x01(\fR\tmediaData\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12T\n" +
	"\x13preferred_transport\x18\x05 \x01(\x0e2#.relaypb.SendMediaRequest.TransportR\x12preferredTransport\"*\n" +
	"\tTransport\x12\b\n" +
	"\x04AUTO\x10\x00\x12\a\n" +
	"\x03DNS\x10\x01\x12\n" +
	"\n" +
	"\x06LIBP2P\x10\x02\"}\n" +
	"\x11SendMediaResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12+\n" +
	"\x11estimated_seconds\x18\x02 \x01(\x05R\x10estimatedSeconds\x12\x1c\n" +
	"\ttransport\x18\x03 \x01(\tR\ttransport\"6\n" +
	"\x15GetMediaStatusRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\xf5\x01\n" +
	"\x13MediaStatusResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.relaypb.MediaStatusResponse.StatusR\x06status\x12!\n" +
	"\fprogress_pct\x18\x03 \x01(\x05R\vprogressPct\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"I\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\v\n" +
	"\aSENDING\x10\x01\x12\f\n" +
	"\bARRIVING\x10\x02\x12\f\n" +
	"\bCOMPLETE\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\"2\n" +
	"\x11CancelSendRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"h\n" +
	"\x10MediaUploadChunk\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\rR\n" +
	"chunkIndex\"\x97\x01\n" +
	"\vSendRequest\x12\x1f\n" +
	"\vpeer_pubkey\x18\x01 \x01(\tR\n" +
	"peerPubkey\x12\x1c\n" +
	"\tplaintext\x18\x02 \x01(\fR\tplaintext\x12.\n" +
	"\x13client_timestamp_ms\x18\x03 \x01(\x04R\x11clientTimestampMs\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\"f\n" +
	"\fSendResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06queued\x18\x02 \x01(\bR\x06queued\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\"\r\n" +
	"\vPollRequest\"D\n" +
	"\fPollResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.relaypb.ReceivedMessageR\bmessages\"\xfd\x01\n" +
	"\x0fReceivedMessage\x12\x1b\n" +
	"\tfrom_peer\x18\x01 \x01(\tR\bfromPeer\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1c\n" +
	"\tplaintext\x18\x03 \x01(\fR\tplaintext\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12.\n" +
	"\x13server_timestamp_ms\x18\x05 \x01(\x04R\x11serverTimestampMs\x12'\n" +
	"\x0fsequence_number\x18\x06 \x01(\x04R\x0esequenceNumber\x12\x19\n" +
	"\bgroup_id\x18\a \x01(\tR\agroupId\"\a\n" +
	"\x05Empty\")\n" +
	"\rRelayEndpoint\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"E\n" +
	"\x0fRelayStatusList\x122\n" +
	"\tendpoints\x18\x01 \x03(\v2\x14.relaypb.RelayStatusR\tendpoints\"\xa8\x01\n" +
	"\vRelayStatus\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\treachable\x18\x02 \x01(\bR\treachable\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\x12#\n" +
	"\rblackout_mode\x18\x05 \x01(\bR\fblackoutMode\"T\n" +
	"\fIdentityInfo\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\">\n" +
	"\bPeerInfo\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\tR\x06pubkey\"7\n" +
	"\x19GenerateInviteCodeRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\"0\n" +
	"\x1aGenerateInviteCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"(\n" +
	"\x12JoinViaCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"[\n" +
	"\x13JoinViaCodeResponse\x12#\n" +
	"\rpeer_nickname\x18\x01 \x01(\tR\fpeerNickname\x12\x1f\n" +
	"\vpeer_pubkey\x18\x02 \x01(\tR\n" +
	"peerPubkey\"<\n" +
	"\x11ListPeersResponse\x12'\n" +
	"\x05peers\x18\x01 \x03(\v2\x11.relaypb.PeerInfoR\x05peers\"O\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0emember_pubkeys\x18\x02 \x03(\tR\rmemberPubkeys\"0\n" +
	"\x13CreateGroupResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\".\n" +
	"\x11LeaveGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"Z\n" +
	"\x18RemoveGroupMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12#\n" +
	"\rmember_pubkey\x18\x02 \x01(\tR\fmemberPubkey\"@\n" +
	"\x12ListGroupsResponse\x12*\n" +
	"\x06groups\x18\x01 \x03(\v2\x12.relaypb.GroupInfoR\x06groups\"\xaa\x01\n" +
	"\tGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fadmin_pubkey\x18\x03 \x01(\tR\vadminPubkey\x12.\n" +
	"\amembers\x18\x04 \x03(\v2\x14.relaypb.GroupMemberR\amembers\x12\x1b\n" +
	"\tkey_epoch\x18\x05 \x01(\x04R\bkeyEpoch\"U\n" +
	"\vGroupMember\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xd2\x01\n" +
	"\x17TransportStatusResponse\x12#\n" +
	"\rdht_connected\x18\x01 \x01(\bR\fdhtConnected\x12+\n" +
	"\x11discovered_relays\x18\x02 \x01(\x05R\x10discoveredRelays\x12#\n" +
	"\rlibp2p_direct\x18\x03 \x01(\bR\flibp2pDirect\x12%\n" +
	"\x0elibp2p_circuit\x18\x04 \x01(\bR\rlibp2pCircuit\x12\x19\n" +
	"\bdns_mode\x18\x05 \x01(\tR\adnsMode\";\n" +
	"\vProfileInfo\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\"R\n" +
	"\x14SetProfilePicRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"P\n" +
	"\x12ProfilePicResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType2\xc2\v\n" +
	"\vRelayClient\x12:\n" +
	"\vSendMessage\x12\x14.relaypb.SendRequest\x1a\x15.relaypb.SendResponse\x12;\n" +
	"\fPollMessages\x12\x14.relaypb.PollRequest\x1a\x15.relaypb.PollResponse\x12:\n" +
	"\x0eGetRelayStatus\x12\x0e.relaypb.Empty\x1a\x18.relaypb.RelayStatusList\x122\n" +
	"\bAddRelay\x12\x16.relaypb.RelayEndpoint\x1a\x0e.relaypb.Empty\x125\n" +
	"\vRemoveRelay\x12\x16.relaypb.RelayEndpoint\x1a\x0e.relaypb.Empty\x124\n" +
	"\vGetIdentity\x12\x0e.relaypb.Empty\x1a\x15.relaypb.IdentityInfo\x12,\n" +
	"\aAddPeer\x12\x11.relaypb.PeerInfo\x1a\x0e.relaypb.Empty\x12F\n" +
	"\x12GetTransportStatus\x12\x0e.relaypb.Empty\x1a .relaypb.TransportStatusResponse\x12B\n" +
	"\tSendMedia\x12\x19.relaypb.SendMediaRequest\x1a\x1a.relaypb.SendMediaResponse\x12N\n" +
	"\x0eGetMediaStatus\x12\x1e.relaypb.GetMediaStatusRequest\x1a\x1c.relaypb.MediaStatusResponse\x128\n" +
	"\n" +
	"CancelSend\x12\x1a.relaypb.CancelSendRequest\x1a\x0e.relaypb.Empty\x12J\n" +
	"\x0fSendMediaStream\x12\x19.relaypb.MediaUploadChunk\x1a\x1a.relaypb.SendMediaResponse(\x01\x12]\n" +
	"\x12GenerateInviteCode\x12\".relaypb.GenerateInviteCodeRequest\x1a#.relaypb.GenerateInviteCodeResponse\x12H\n" +
	"\vJoinViaCode\x12\x1b.relaypb.JoinViaCodeRequest\x1a\x1c.relaypb.JoinViaCodeResponse\x12/\n" +
	"\n" +
	"RemovePeer\x12\x11.relaypb.PeerInfo\x1a\x0e.relaypb.Empty\x127\n" +
	"\tListPeers\x12\x0e.relaypb.Empty\x1a\x1a.relaypb.ListPeersResponse\x12H\n" +
	"\vCreateGroup\x12\x1b.relaypb.CreateGroupRequest\x1a\x1c.relaypb.CreateGroupResponse\x129\n" +
	"\n" +
	"ListGroups\x12\x0e.relaypb.Empty\x1a\x1b.relaypb.ListGroupsResponse\x128\n" +
	"\n" +
	"LeaveGroup\x12\x1a.relaypb.LeaveGroupRequest\x1a\x0e.relaypb.Empty\x12F\n" +
	"\x11RemoveGroupMember\x12!.relaypb.RemoveGroupMemberRequest\x1a\x0e.relaypb.Empty\x125\n" +
	"\rUpdateProfile\x12\x14.relaypb.ProfileInfo\x1a\x0e.relaypb.Empty\x12<\n" +
	"\rGetProfilePic\x12\x0e.relaypb.Empty\x1a\x1b.relaypb.ProfilePicResponse\x12>\n" +
	"\rSetProfilePic\x12\x1d.relaypb.SetProfilePicRequest\x1a\x0e.relaypb.EmptyB+Z)github.com/user/dns-transport/pkg/relaypbb\x06proto3"

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData []byte
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)))
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_relay_proto_goTypes = []any{
	(SendMediaRequest_Transport)(0),    // 0: relaypb.SendMediaRequest.Transport
	(MediaStatusResponse_Status)(0),    // 1: relaypb.MediaStatusResponse.Status
	(*SendMediaRequest)(nil),           // 2: relaypb.SendMediaRequest
	(*SendMediaResponse)(nil),          // 3: relaypb.SendMediaResponse
	(*GetMediaStatusRequest)(nil),      // 4: relaypb.GetMediaStatusRequest
	(*MediaStatusResponse)(nil),        // 5: relaypb.MediaStatusResponse
	(*CancelSendRequest)(nil),          // 6: relaypb.CancelSendRequest
	(*MediaUploadChunk)(nil),           // 7: relaypb.MediaUploadChunk
	(*SendRequest)(nil),                // 8: relaypb.SendRequest
	(*SendResponse)(nil),               // 9: relaypb.SendResponse
	(*PollRequest)(nil),                // 10: relaypb.PollRequest
	(*PollResponse)(nil),               // 11: relaypb.PollResponse
	(*ReceivedMessage)(nil),            // 12: relaypb.ReceivedMessage
	(*Empty)(nil),                      // 13: relaypb.Empty
	(*RelayEndpoint)(nil),              // 14: relaypb.RelayEndpoint
	(*RelayStatusList)(nil),            // 15: relaypb.RelayStatusList
	(*RelayStatus)(nil),                // 16: relaypb.RelayStatus
	(*IdentityInfo)(nil),               // 17: relaypb.IdentityInfo
	(*PeerInfo)(nil),                   // 18: relaypb.PeerInfo
	(*GenerateInviteCodeRequest)(nil),  // 19: relaypb.GenerateInviteCodeRequest
	(*GenerateInviteCodeResponse)(nil), // 20: relaypb.GenerateInviteCodeResponse
	(*JoinViaCodeRequest)(nil),         // 21: relaypb.JoinViaCodeRequest
	(*JoinViaCodeResponse)(nil),        // 22: relaypb.JoinViaCodeResponse
	(*ListPeersResponse)(nil),          // 23: relaypb.ListPeersResponse
	(*CreateGroupRequest)(nil),         // 24: relaypb.CreateGroupRequest
	(*CreateGroupResponse)(nil),        // 25: relaypb.CreateGroupResponse
	(*LeaveGroupRequest)(nil),          // 26: relaypb.LeaveGroupRequest
	(*RemoveGroupMemberRequest)(nil),   // 27: relaypb.RemoveGroupMemberRequest
	(*ListGroupsResponse)(nil),         // 28: relaypb.ListGroupsResponse
	(*GroupInfo)(nil),                  // 29: relaypb.GroupInfo
	(*GroupMember)(nil),                // 30: relaypb.GroupMember
	(*TransportStatusResponse)(nil),    // 31: relaypb.TransportStatusResponse
	(*ProfileInfo)(nil),                // 32: relaypb.ProfileInfo
	(*SetProfilePicRequest)(nil),       // 33: relaypb.SetProfilePicRequest
	(*ProfilePicResponse)(nil),         // 34: relaypb.ProfilePicResponse
}
var file_relay_proto_depIdxs = []int32{
	0,  // 0: relaypb.SendMediaRequest.preferred_transport:type_name -> relaypb.SendMediaRequest.Transport
	1,  // 1: relaypb.MediaStatusResponse.status:type_name -> relaypb.MediaStatusResponse.Status
	12, // 2: relaypb.PollResponse.messages:type_name -> relaypb.ReceivedMessage
	16, // 3: relaypb.RelayStatusList.endpoints:type_name -> relaypb.RelayStatus
	18, // 4: relaypb.ListPeersResponse.peers:type_name -> relaypb.PeerInfo
	29, // 5: relaypb.ListGroupsResponse.groups:type_name -> relaypb.GroupInfo
	30, // 6: relaypb.GroupInfo.members:type_name -> relaypb.GroupMember
	8,  // 7: relaypb.RelayClient.SendMessage:input_type -> relaypb.SendRequest
	10, // 8: relaypb.RelayClient.PollMessages:input_type -> relaypb.PollRequest
	13, // 9: relaypb.RelayClient.GetRelayStatus:input_type -> relaypb.Empty
	14, // 10: relaypb.RelayClient.AddRelay:input_type -> relaypb.RelayEndpoint
	14, // 11: relaypb.RelayClient.RemoveRelay:input_type -> relaypb.RelayEndpoint
	13, // 12: relaypb.RelayClient.GetIdentity:input_type -> relaypb.Empty
	18, // 13: relaypb.RelayClient.AddPeer:input_type -> relaypb.PeerInfo
	13, // 14: relaypb.RelayClient.GetTransportStatus:input_type -> relaypb.Empty
	2,  // 15: relaypb.RelayClient.SendMedia:input_type -> relaypb.SendMediaRequest
	4,  // 16: relaypb.RelayClient.GetMediaStatus:input_type -> relaypb.GetMediaStatusRequest
	6,  // 17: relaypb.RelayClient.CancelSend:input_type -> relaypb.CancelSendRequest
	7,  // 18: relaypb.RelayClient.SendMediaStream:input_type -> relaypb.MediaUploadChunk
	19, // 19: relaypb.RelayClient.GenerateInviteCode:input_type -> relaypb.GenerateInviteCodeRequest
	21, // 20: relaypb.RelayClient.JoinViaCode:input_type -> relaypb.JoinViaCodeRequest
	18, // 21: relaypb.RelayClient.RemovePeer:input_type -> relaypb.PeerInfo
	13, // 22: relaypb.RelayClient.ListPeers:input_type -> relaypb.Empty
	24, // 23: relaypb.RelayClient.CreateGroup:input_type -> relaypb.CreateGroupRequest
	13, // 24: relaypb.RelayClient.ListGroups:input_type -> relaypb.Empty
	26, // 25: relaypb.RelayClient.LeaveGroup:input_type -> relaypb.LeaveGroupRequest
	27, // 26: relaypb.RelayClient.RemoveGroupMember:input_type -> relaypb.RemoveGroupMemberRequest
	32, // 27: relaypb.RelayClient.UpdateProfile:input_type -> relaypb.ProfileInfo
	13, // 28: relaypb.RelayClient.GetProfilePic:input_type -> relaypb.Empty
	33, // 29: relaypb.RelayClient.SetProfilePic:input_type -> relaypb.SetProfilePicRequest
	9,  // 30: relaypb.RelayClient.SendMessage:output_type -> relaypb.SendResponse
	11, // 31: relaypb.RelayClient.PollMessages:output_type -> relaypb.PollResponse
	15, // 32: relaypb.RelayClient.GetRelayStatus:output_type -> relaypb.RelayStatusList
	13, // 33: relaypb.RelayClient.AddRelay:output_type -> relaypb.Empty
	13, // 34: relaypb.RelayClient.RemoveRelay:output_type -> relaypb.Empty
	17, // 35: relaypb.RelayClient.GetIdentity:output_type -> relaypb.IdentityInfo
	13, // 36: relaypb.RelayClient.AddPeer:output_type -> relaypb.Empty
	31, // 37: relaypb.RelayClient.GetTransportStatus:output_type -> relaypb.TransportStatusResponse
	3,  // 38: relaypb.RelayClient.SendMedia:output_type -> relaypb.SendMediaResponse
	5,  // 39: relaypb.RelayClient.GetMediaStatus:output_type -> relaypb.MediaStatusResponse
	13, // 40: relaypb.RelayClient.CancelSend:output_type -> relaypb.Empty
	3,  // 41: relaypb.RelayClient.SendMediaStream:output_type -> relaypb.SendMediaResponse
	20, // 42: relaypb.RelayClient.GenerateInviteCode:output_type -> relaypb.GenerateInviteCodeResponse
	22, // 43: relaypb.RelayClient.JoinViaCode:output_type -> relaypb.JoinViaCodeResponse
	13, // 44: relaypb.RelayClient.RemovePeer:output_type -> relaypb.Empty
	23, // 45: relaypb.RelayClient.ListPeers:output_type -> relaypb.ListPeersResponse
	25, // 46: relaypb.RelayClient.CreateGroup:output_type -> relaypb.CreateGroupResponse
	28, // 47: relaypb.RelayClient.ListGroups:output_type -> relaypb.ListGroupsResponse
	13, // 48: relaypb.RelayClient.LeaveGroup:output_type -> relaypb.Empty
	13, // 49: relaypb.RelayClient.RemoveGroupMember:output_type -> relaypb.Empty
	13, // 50: relaypb.RelayClient.UpdateProfile:output_type -> relaypb.Empty
	34, // 51: relaypb.RelayClient.GetProfilePic:output_type -> relaypb.ProfilePicResponse
	13, // 52: relaypb.RelayClient.SetProfilePic:output_type -> relaypb.Empty
	30, // [30:53] is the sub-list for method output_type
	7,  // [7:30] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		EnumInfos:         file_relay_proto_enumTypes,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
