// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/relay.proto

package relaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayClient_SendMessage_FullMethodName        = "/relaypb.RelayClient/SendMessage"
	RelayClient_PollMessages_FullMethodName       = "/relaypb.RelayClient/PollMessages"
	RelayClient_GetRelayStatus_FullMethodName     = "/relaypb.RelayClient/GetRelayStatus"
	RelayClient_AddRelay_FullMethodName           = "/relaypb.RelayClient/AddRelay"
	RelayClient_RemoveRelay_FullMethodName        = "/relaypb.RelayClient/RemoveRelay"
	RelayClient_GetIdentity_FullMethodName        = "/relaypb.RelayClient/GetIdentity"
	RelayClient_AddPeer_FullMethodName            = "/relaypb.RelayClient/AddPeer"
	RelayClient_GetTransportStatus_FullMethodName = "/relaypb.RelayClient/GetTransportStatus"
)

// RelayClientClient is the client API for RelayClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayClientClient interface {
	SendMessage(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	PollMessages(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error)
	GetRelayStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RelayStatusList, error)
	AddRelay(ctx context.Context, in *RelayEndpoint, opts ...grpc.CallOption) (*Empty, error)
	RemoveRelay(ctx context.Context, in *RelayEndpoint, opts ...grpc.CallOption) (*Empty, error)
	GetIdentity(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentityInfo, error)
	AddPeer(ctx context.Context, in *PeerInfo, opts ...grpc.CallOption) (*Empty, error)
	GetTransportStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TransportStatusResponse, error)
}

type relayClientClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayClientClient(cc grpc.ClientConnInterface) RelayClientClient {
	return &relayClientClient{cc}
}

func (c *relayClientClient) SendMessage(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, RelayClient_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) PollMessages(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollResponse)
	err := c.cc.Invoke(ctx, RelayClient_PollMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) GetRelayStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RelayStatusList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayStatusList)
	err := c.cc.Invoke(ctx, RelayClient_GetRelayStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) AddRelay(ctx context.Context, in *RelayEndpoint, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_AddRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) RemoveRelay(ctx context.Context, in *RelayEndpoint, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_RemoveRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) GetIdentity(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentityInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityInfo)
	err := c.cc.Invoke(ctx, RelayClient_GetIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) AddPeer(ctx context.Context, in *PeerInfo, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RelayClient_AddPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClientClient) GetTransportStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TransportStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransportStatusResponse)
	err := c.cc.Invoke(ctx, RelayClient_GetTransportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayClientServer is the server API for RelayClient service.
// All implementations must embed UnimplementedRelayClientServer
// for forward compatibility.
type RelayClientServer interface {
	SendMessage(context.Context, *SendRequest) (*SendResponse, error)
	PollMessages(context.Context, *PollRequest) (*PollResponse, error)
	GetRelayStatus(context.Context, *Empty) (*RelayStatusList, error)
	AddRelay(context.Context, *RelayEndpoint) (*Empty, error)
	RemoveRelay(context.Context, *RelayEndpoint) (*Empty, error)
	GetIdentity(context.Context, *Empty) (*IdentityInfo, error)
	AddPeer(context.Context, *PeerInfo) (*Empty, error)
	GetTransportStatus(context.Context, *Empty) (*TransportStatusResponse, error)
	mustEmbedUnimplementedRelayClientServer()
}

// UnimplementedRelayClientServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayClientServer struct{}

func (UnimplementedRelayClientServer) SendMessage(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedRelayClientServer) PollMessages(context.Context, *PollRequest) (*PollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollMessages not implemented")
}
func (UnimplementedRelayClientServer) GetRelayStatus(context.Context, *Empty) (*RelayStatusList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelayStatus not implemented")
}
func (UnimplementedRelayClientServer) AddRelay(context.Context, *RelayEndpoint) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRelay not implemented")
}
func (UnimplementedRelayClientServer) RemoveRelay(context.Context, *RelayEndpoint) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRelay not implemented")
}
func (UnimplementedRelayClientServer) GetIdentity(context.Context, *Empty) (*IdentityInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentity not implemented")
}
func (UnimplementedRelayClientServer) AddPeer(context.Context, *PeerInfo) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPeer not implemented")
}
func (UnimplementedRelayClientServer) GetTransportStatus(context.Context, *Empty) (*TransportStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransportStatus not implemented")
}
func (UnimplementedRelayClientServer) mustEmbedUnimplementedRelayClientServer() {}
func (UnimplementedRelayClientServer) testEmbeddedByValue()                     {}

// UnsafeRelayClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayClientServer will
// result in compilation errors.
type UnsafeRelayClientServer interface {
	mustEmbedUnimplementedRelayClientServer()
}

func RegisterRelayClientServer(s grpc.ServiceRegistrar, srv RelayClientServer) {
	// If the following call panics, it indicates UnimplementedRelayClientServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayClient_ServiceDesc, srv)
}

func _RelayClient_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).SendMessage(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_PollMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).PollMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_PollMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).PollMessages(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_GetRelayStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).GetRelayStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_GetRelayStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).GetRelayStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_AddRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayEndpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).AddRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_AddRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).AddRelay(ctx, req.(*RelayEndpoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_RemoveRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayEndpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).RemoveRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_RemoveRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).RemoveRelay(ctx, req.(*RelayEndpoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_GetIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).GetIdentity(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_AddPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).AddPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_AddPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).AddPeer(ctx, req.(*PeerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayClient_GetTransportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayClientServer).GetTransportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayClient_GetTransportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayClientServer).GetTransportStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayClient_ServiceDesc is the grpc.ServiceDesc for RelayClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relaypb.RelayClient",
	HandlerType: (*RelayClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _RelayClient_SendMessage_Handler,
		},
		{
			MethodName: "PollMessages",
			Handler:    _RelayClient_PollMessages_Handler,
		},
		{
			MethodName: "GetRelayStatus",
			Handler:    _RelayClient_GetRelayStatus_Handler,
		},
		{
			MethodName: "AddRelay",
			Handler:    _RelayClient_AddRelay_Handler,
		},
		{
			MethodName: "RemoveRelay",
			Handler:    _RelayClient_RemoveRelay_Handler,
		},
		{
			MethodName: "GetIdentity",
			Handler:    _RelayClient_GetIdentity_Handler,
		},
		{
			MethodName: "AddPeer",
			Handler:    _RelayClient_AddPeer_Handler,
		},
		{
			MethodName: "GetTransportStatus",
			Handler:    _RelayClient_GetTransportStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/relay.proto",
}
